#
# Copyright (c) 2022 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/.github.
#
# SPDX-License-Identifier: Apache-2.0
#
MD041: false