#
# Copyright (c) 2022 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/.github.
#
# SPDX-License-Identifier: Apache-2.0
#
name: 'Close Stale Issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-message: 'This issue or PR has been marked stale because it has been open for 90 days with no activity. This issue or PR will be automatically closed in 5 days if no further activity occurs.'
          days-before-stale: 90
          days-before-close: 5
          exempt-issue-labels: 'bug,could have,documentation,dependencies,enhancement,should have'
