#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/.github.
#
# SPDX-License-Identifier: Apache-2.0
#
name: 'Herdstat Analysis'
on:
  workflow_dispatch:
  schedule:
    # Runs every at midnight
    - cron: '0 0 * * *'
jobs:
  herdstat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.HERDSTAT_PAT }}
      - uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.CS_MINION_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CS_MINION_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - uses: herdstat/herdstat-action@v0.9.1
        with:
          version: v0.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.HERDSTAT_PAT }}
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: cs-minion
          author_email: rng_cr_carbynestack@bosch.com
          add: 'profile/contribution-graph.svg'
          message: 'Update contribution graph'
