#
# Copyright (c) 2022 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/.github.
#
# SPDX-License-Identifier: Apache-2.0
#
name: 'Close Stale Issues and PRs'
on:

  # Allows workflow to be reusable.  @see https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:

jobs:
  stale:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-message: 'This issue or PR has been marked stale because it has been open for 90 days with no activity. This issue or PR will be automatically closed in 5 days if no further activity occurs.'
          days-before-stale: 90
          days-before-close: 5
          exempt-issue-labels: 'needs-triage,priority/backlog,priority/critical-urgent,triage/needs-information,priority/awaiting-more-evidence,lifecycle/frozen,lifecycle/stale,lifecycle/rotten,triage/unresolved,triage/duplicate,triage/not-reproducible,triage/accepted,priority/important-longterm,priority/important-soon,kind/documentation,kind/feature,kind/cleanup,kind/bug,kind/support,help-wanted'
